# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'
  VULKAN_SDK: C:/VulkanSDK/1.3.224.1
  VULKAN_VERSION: 1.3.224.1

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      set -ex
                curl -L -o "VulkanSDK-1.3.224.1-Installer.exe" "https://sdk.lunarg.com/sdk/download/1.3.224.1/windows/VulkanSDK-1.3.224.1-Installer.exe"
                # This makes sure we wait for the vulkan SDK to complete installation
                _=$(echo "VulkanSDK-1.3.224.1-Installer.exe /S" | cmd)
                curl -L -o "VulkanRT-1.3.224.1-Components.zip" "https://sdk.lunarg.com/sdk/download/1.3.224.1/windows/VulkanRT-1.3.224.1-Components.zip"
                unzip VulkanRT-1.3.224.1-Components.zip
                cp VulkanRT-1.3.224.1-Components/x64/vulkaninfo.exe $VULKAN_SDK/Bin
                cp VulkanRT-1.3.224.1-Components/x64/vulkan-1.dll $VULKAN_SDK/Bin
- task: BatchScript@1
  inputs:
    filename: 'scripts/Windows-GenerateProject.bat'
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'
    platform: 'Editor'
    configuration: 'Debug'
